image: proboci/lamp:ubuntu14.04-apache2.4-mysql5.5-php5.6
assets:     
  - d7testsite.sql.gz
steps:
  - name: Drupal 7 Probo site setup.
    plugin: Drupal
    drupalVersion: 7
    database: d7testsite.sql.gz
    subDirectory: docroot
    databaseGzipped: true
    databaseUpdates: false
    revertFeatures: false
    clearCaches: true
