image: proboci/ubuntu-14.04-lamp:php7.0-nightly
assets:     
  - d7testsite.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    drupalVersion: 7
    database: d7testsite.sql.gz
    subDirectory: docroot
    databaseGzipped: true
    databaseUpdates: false
    revertFeatures: false
    clearCaches: true
  - name: Check versions.
    plugin: Script
    script:
      - echo "checking bower version..."
      - bower list
      - echo "checking grunt version..."
      - grunt -version
      - echo "checking gulp version..."
      - gulp -v
      - echo "checking yarn version..."
      - yarn version
